### ISSUE TITLE
Нет файла с зависимостями 

### ISSUE THREAD

**Issue by codershkoder** [notrurs/zombie_shooter_026#2]
Добавьте, пожалуйста, а то не сразу понятно, что нужно

**Comment by notrurs** [comment]
Да, спасибо, что заметил

**Comment by notrurs** [comment]
Добавлено в [3f30e21
](https://github.com/notrurs/zombie_shooter_026/commit/3f30e21e9dc015c9312664337ead66919d72ffcf)
